### PR TITLE
Implement league standings

### PR DESCRIPTION
**Pull request by cacheflow**
-This adds a new namespace called leagueStandings under stats, which
returns the NBA's standings for that year.
-Included the necessary API standings endpoint.
-Added a new transform to segment standings by conference and divison.
-Lastly, included a test and updated Readme on how to use it.

### CODE REVIEW

**Comment by cacheflow** [comment]
Also, I'm not entirely sure if the `standings.json` file is needed along with the updateStandings function found in `index.js`. I was trying to follow your convention, but not entirely sure if it is needed. Could you explain why you're caching the teams and players? :D

**Comment by brah** [comment]
Wow! Looks great. Thanks @cacheflow-lil guy. Looking forward to this getting merged in!

**Comment by avijohnson** [comment]
+1 @cacheflow @bttmly

**Comment by bttmly** [comment]
Shoot, sorry, forgot to bump `nba-client-template` in this package after this commit https://github.com/bttmly/nba-client-template/pull/3

This functionality is automatically added once we use the new template, so we don't need to make any JS source changes. https://github.com/bttmly/nba/commit/04667cdc050e7d298bad9ca75ca47fd0831a59dd

Seems to work great, feel free to reopen if you hit any issues. Latest is `nba@4.1.0`

**Comment by cacheflow** [comment]
Cool cool. I'll check it out. Thanks @bttmly.

**Pull request closed without merging**
