### PR TITLE
Add endpoints

### PR DESCRIPTION
**Pull request by jcostello93**
NOTE: there is a corresponding pull request for nba-client-template

This pull request adds 2 endpoints from the /stats namespace to the src/stats.js file: 
- teamPlayerOnOffDetails
- playerCompare

It also adds 8 endpoints and modifies the schedule endpoint from the /data namespace to the src/data.js file: 

- schedule (modified)
- teamSchedule
- previewArticle
- recapArticle
- leadTracker
- playoffsBracket
- teamLeaders
- teamStatsRankings
- coaches

### CODE REVIEW

**Comment by bttmly** [comment]
awesome! would you mind adding some basic [tests](https://github.com/bttmly/nba/blob/master/test/integration/data.js) for these before I merge it?

**Comment by jcostello93** [comment]
Tests *should* be added to the request

**Comment by bttmly** [comment]
Thank you!

**Comment by bttmly** [comment]
Did these tests pass locally for you? I have some failures.

**Pull request merged**
